### ISSUE TITLE
Support for namespaced attributes

### ISSUE THREAD

**Issue by indiosmo** [sporacid/spore-codegen#29]
The use case is again large codebases.

Custom attributes are usually namespaced like `struct [[proj::serializable]]` or something.
This gets exported to the json AST representation as:

<pre><code>
...
  "attributes": {
     <b>"proj::serializable"</b>: {
      "full_name": "proj_serializable",
      "id": 18,
      "name": "json",
      "scope": "mil",
      "values": {}
    }
  }
...
</code></pre>

This can't be used from inside inja variables like `{{ field.attributes.proj::serializable.values.name }}`.

This issue is a starting point to think about possible alternatives, one of them being simply substituting invalid template characters, e.g. substitute `_` for `:`.

**Comment by sporacid** [comment]
Definitely, I'll have a look how to make them work!
