### ISSUE TITLE
[cppast] Parser errors with Boost types

### ISSUE THREAD

**Issue by indiosmo** [sporacid/spore-codegen#33]
See https://github.com/foonathan/cppast/issues/103

Setting the following in `codegen_app.hpp` solves it:

`cppast_config.remove_comments_in_macro(true);`

Let me know if you want to just set it hardcoded or make it an option.

**Comment by sporacid** [comment]
Good catch, we can set it to true by default for now. I think we can skip the option, because I'm not sure at this point whether it's something that should always be set to true, or if some project might benefit from setting it to false.
